spring:
  application:
    name: "activiti"
  security:
    user:
      name: ${SECURITY_USERNAME}
      password: ${SECURITY_PASSWORD}
  activiti:
    database-schema-update: true
    check-process-definitions: false
    process-engine-name: default
    dbHistoryUsed: true
    historyLevel: full
  datasource:
    activiti:
      url: ${ACTIVITI_DB_URL}
      driver-class-name: org.postgresql.Driver
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      platform: postgresql
      hikari:
        connectionTimeout: 30000
        idleTimeout: 600000
        maxLifetime: 1800000
    adaptflow:
      url: ${ADAPTFLOW_DB_URL}
      driver-class-name: org.postgresql.Driver
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      platform: postgresql
      hikari:
        connectionTimeout: 30000
        idleTimeout: 600000
        maxLifetime: 1800000
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  flyway:
    enabled: false
    ignore-missing-migrations: true
    outOfOrder: true